config/routes.rb
Rails.application.routes.draw do
  resources :letcheeses
  resources :cheeses
  get '/signup', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'create_session'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  root 'application#index'
end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
end

app/models/letcheese.rb
class Letcheese < ActiveRecord::Base
  belongs_to user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :letchesse
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_filter :current_user

  include ApplicationHelper

  def index
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if current_user == nil
    end
  end
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :allowed_to_modify_cheese, only: [:edit, :update, :destroy]


  def index
    @cheeses = Cheese.all
  end


  def show
    set_cheese
  end

  def new
    @cheese = Cheese.new
  end

  def edit
    set_cheese
  end


  def create
    @cheese = Cheese.new(cheese_params)

    respond_to do |format|
      if @cheese.save
        format.html { redirect_to @cheese, notice: 'Cheese was successfully created.' }
        format.json { render :show, status: :created, location: @cheese }
      else
        format.html { render :new }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @cheese.update(cheese_params)
        format.html { redirect_to @cheese, notice: 'Cheese was successfully updated.' }
        format.json { render :show, status: :ok, location: @cheese }
      else
        format.html { render :edit }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cheese.destroy
    respond_to do |format|
      format.html { redirect_to cheeses_url, notice: 'Cheese was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_cheese
    @cheese = Cheese.find(params[:id])
  end

  def cheese_params
    params.require(:cheese).permit(:cheese_name, :category)
  end

  def allowed_to_modify_cheese
  set_cheese
    if @cheese.user.id != current_user.id
      redirect_to cheeses_path, alert: "Users can only modify their cheeses."
    end
  end
end

app/controllers/letcheeses_controller.rb
class LetcheesesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :allowed_to_modify_addcheese, only: [:edit, :update, :destroy]


  def index
    @letcheeses = Letcheese.all
  end


  def show
    set_letcheese
  end


  def new
    @letcheese = Letcheese.new
  end

  def edit
  end

  def create
    @letcheese = Letcheese.new(letcheese_params)

    respond_to do |format|
      if @letcheese.save
        format.html { redirect_to @letcheese, notice: 'Letcheese was successfully created.' }
        format.json { render :show, status: :created, location: @letcheese }
      else
        format.html { render :new }
        format.json { render json: @letcheese.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @letcheese.update(letcheese_params)
        format.html { redirect_to @letcheese, notice: 'Letcheese was successfully updated.' }
        format.json { render :show, status: :ok, location: @letcheese }
      else
        format.html { render :edit }
        format.json { render json: @letcheese.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @letcheese.destroy
    respond_to do |format|
      format.html { redirect_to letcheeses_url, notice: 'Letcheese was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_letcheese
    @letcheese = Letcheese.find(params[:id])
  end

  def letcheese_params
    params.require(:letcheese).permit(:own_cheeses)
  end

  def allowed_to_modify_addcheese
  set_cheese
    if @letcheese.user.id != current_user.id
      redirect_to cheeses_path, alert: "Users can only modify their cheeses."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_username(params[:username])
    if user != nil && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Success'
    else
      flash[:alert] = 'Email or password did not match'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :allowed_to_modify_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    set_user
  end

  def new
    @user = User.new
  end

  def edit
    set_user
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def allowed_to_modify_user
    set_user
    if @user.id != current_user.id
      redirect_to users_path, alert: "Users can only modify themselves."
    end
  end
end

app/controllers/welcomecontroller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    unless @current_user.nil?
      true
    end
  end
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/helpers/letcheeses_helper.rb
module LetcheesesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<%= react_component("Welcome") %>

app/views/cheeses/_form.html.erb
<%= form_for(@cheese) do |f| %>
  <% if @cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% @cheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cheese_name %><br>
    <%= f.text_field :cheese_name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheeses/edit.html.erb
<h1>Editing Cheese</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheese %> |
<%= link_to 'Back', cheeses_path %>

app/views/cheeses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cheeses</h1>

<table>
  <thead>
    <tr>
      <th>Cheese name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cheeses.each do |cheese| %>
      <tr>
        <td><%= cheese.cheese_name %></td>
        <td><%= cheese.category %></td>
        <td><%= link_to 'Show', cheese %></td>
        <td><%= link_to 'Edit', edit_cheese_path(cheese) %></td>
        <td><%= link_to 'Destroy', cheese, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cheese', new_cheese_path %>

app/views/cheeses/new.html.erb
<h1>New Cheese</h1>

<%= render 'form' %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cheese name:</strong>
  <%= @cheese.cheese_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @cheese.category %>
</p>

<%= link_to 'Edit', edit_cheese_path(@cheese) %> |
<%= link_to 'Back', cheeses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactAndCheese</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class='main'>
    <div class='row'>
      <div class='col-sm-4'>
        <h1><%= link_to 'Cheese Factory', root_path %></h1>
      </div>
    </div>
  </header>
<%= react_component("Navigation") %>
<%= yield %>

</body>
</html>

app/views/letcheeses/_form.html.erb
<%= form_for(@letcheese) do |f| %>
  <% if @letcheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@letcheese.errors.count, "error") %> prohibited this letcheese from being saved:</h2>

      <ul>
      <% @letcheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :own_cheeses %><br>
    <%= f.text_field :own_cheeses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/letcheeses/edit.html.erb
<h1>Editing Letcheese</h1>

<%= render 'form' %>

<%= link_to 'Show', @letcheese %> |
<%= link_to 'Back', letcheeses_path %>

app/views/letcheeses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Letcheeses</h1>

<table>
  <thead>
    <tr>
      <th>Own cheeses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @letcheeses.each do |letcheese| %>
      <tr>
        <td><%= letcheese.own_cheeses %></td>
        <td><%= link_to 'Show', letcheese %></td>
        <td><%= link_to 'Edit', edit_letcheese_path(letcheese) %></td>
        <td><%= link_to 'Destroy', letcheese, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Letcheese', new_letcheese_path %>

app/views/letcheeses/new.html.erb
<h1>New Letcheese</h1>

<%= render 'form' %>

<%= link_to 'Back', letcheeses_path %>

app/views/letcheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Own cheeses:</strong>
  <%= @letcheese.own_cheeses %>
</p>

<%= link_to 'Edit', edit_letcheese_path(@letcheese) %> |
<%= link_to 'Back', letcheeses_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>